name: CI

on:
  push:
    branches:
      - develop

jobs:

  frontend-build-and-test:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Find current PR
      id: findPr
      uses: jwalton/gh-find-current-pr@v1

    - name: Jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        prnumber: ${{ steps.findPr.outputs.number }}
        working-directory: ./client/memo-minder-web
        github-token: ${{ secrets.TOKEN_FOR_MEMO }}
        annotations: none
        test-script: npm test
        output: report-markdown
            
  backend-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Test backend
      run: |
        cd memo-backend
        npm install
        npm test
