name: CI

on:
  push:
    branches:
      - develop

jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Build and test frontend with coverage
      run: |
        cd client/memo-minder-web
        npm install
        npm run build
        npm test -- --coverage --coverageReporters=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: frontend-coverage-report
        path: client/memo-minder-web/coverage/index.html

    - name: Set coverage report output
      run: echo "coverage_report=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_ENV

    - name: Display coverage report link
      run: echo "Coverage report is available at $coverage_report"

  backend-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Test backend
      run: |
        cd memo-backend
        npm install
        npm test
