name: CI

on:
  push:
    branches:
      - develop

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Change directory to memo-minder-web
      run: cd client/memo-minder-web

    - name: Install frontend dependencies
      run: npm install

    - name: Run frontend tests
      run: npm test
